title: comsoft@WHU
description: 武汉大学comsoft组的知识分享!
theme: just-the-docs

url: https://comsoftWHU.github.io
markdown: kramdown
markdown_ext: "md"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

math: katex