title: comsoft@WHU
description: 武汉大学comsoft组的知识分享!
theme: just-the-docs

url: https://comsoftWHU.github.io
markdown: kramdown
markdown_ext: "md"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.6.0"

aux_links:
  Just the Docs on GitHub:
    - https://github.com/just-the-docs/just-the-docs

math: katex